### ISSUE TITLE
Choose a logo for Julia-i18n

### ISSUE THREAD

**Issue by Ismael-VC** [Julia-i18n/julia-i18n#5]
@waldyrious do we have a winner? 😸

**Comment by waldyrious** [comment]
(For context, previous discussion happened in Gitter chats and on [this julia-users thread](https://groups.google.com/d/topic/julia-users/rahjsS_OW4g/discussion).)

I was hoping @innerlee would clarify [his message](https://gitter.im/JuliaLangEs/julia-i18n?at=57f590243c59573f6f103f93):

> I prefer we use 朱 in the J version. People seldom use 吉 in translation of names. when Chinese people see a red 吉 enclosed by circle or square, the first response is the following image:
> ![](https://files.gitter.im/JuliaLangEs/julia-i18n/ovtK/ji.PNG)

To which I [asked](https://gitter.im/JuliaLangEs/julia-i18n?at=57f59608f69c94ad0991a061):

> what does that image mean?

Awaiting his response, otherwise I'll stick with 吉 for symmetry with the other ones (as in being a representation of the "J" sound, rather than the "Ju" sound).

**Comment by innerlee** [comment]
The character itself means best wishes and good luck. This character was written in a big red paper and pasted on doors (as in the image) in the Spring Festival. This was an old tradition ([wiki](https://en.wikipedia.org/wiki/Fai_Chun)) way back thousands of years ago. My concern was that this character seldom relates to technology. I did not mean `good wish` is not proper but just felt that it lacks a sense of formality and profession (well, to me). If most of us prefer the `pronunciation and shape` rather than the `extended meaning`, it is indeed a good choice. Hope this clarify what I meant :)

**Comment by waldyrious** [comment]
Ok, I'm glad. I was afraid it carried some negative meaning. Considering that single characters do have semantic meaning in Chinese while they are generally meaningless in other scripts, I would think that as long as the meaning in Chinese isn't a negative one, it shouldn't guide our decision, which was based on a different criterion, which would be broken if we opened an exception.

So given your approval, I think we can close this and use the version with 吉 😄
